var rowData = [
        {
            "QUALITY": "Filafil",
            "DESIGN": 254,
            "FAC_PCS": 30,
            "FAC_MTRS": 2114.2,
            "PAC_PCS": 4,
            "PAC_MTRS": 424,
            "ORD_MTRS": 0,
            "BAL_QTY": 2538.2,
            "DYG_PCS": 0,
            "DYG_MTRS": 0,
            "PO_MTRS": 0,
            "BASE_DESIGN": null,
            "SIMILAR_DESIGN": null,
            "BASE_QUALITY": null,
            "SIMILAR_QUALITY": null,
            "dsnoid": 12
        },
        {
            "QUALITY": "Filafil",
            "DESIGN": 251,
            "FAC_PCS": 69,
            "FAC_MTRS": 4710.4018,
            "PAC_PCS": 0,
            "PAC_MTRS": 0,
            "ORD_MTRS": 250,
            "BAL_QTY": 4460.4018,
            "DYG_PCS": 0,
            "DYG_MTRS": 0,
            "PO_MTRS": 0,
            "BASE_DESIGN": null,
            "SIMILAR_DESIGN": null,
            "BASE_QUALITY": null,
            "SIMILAR_QUALITY": null,
            "dsnoid": 3439
        },
        {
            "QUALITY": "Filafil",
            "DESIGN": 256,
            "FAC_PCS": 40,
            "FAC_MTRS": 2734.4,
            "PAC_PCS": 0,
            "PAC_MTRS": 0,
            "ORD_MTRS": 0,
            "BAL_QTY": 2734.4,
            "DYG_PCS": 0,
            "DYG_MTRS": 0,
            "PO_MTRS": 0,
            "BASE_DESIGN": null,
            "SIMILAR_DESIGN": null,
            "BASE_QUALITY": null,
            "SIMILAR_QUALITY": null,
            "dsnoid": 8715
        },
        {
            "QUALITY": "Filafil",
            "DESIGN": 258,
            "FAC_PCS": 23,
            "FAC_MTRS": 899.2,
            "PAC_PCS": 0,
            "PAC_MTRS": 0,
            "ORD_MTRS": 0,
            "BAL_QTY": 899.2,
            "DYG_PCS": 0,
            "DYG_MTRS": 0,
            "PO_MTRS": 1000,
            "BASE_DESIGN": null,
            "SIMILAR_DESIGN": null,
            "BASE_QUALITY": null,
            "SIMILAR_QUALITY": null,
            "dsnoid": 9763
        },
        {
            "QUALITY": "Filafil",
            "DESIGN": 253,
            "FAC_PCS": 73,
            "FAC_MTRS": 4544.0032,
            "PAC_PCS": 0,
            "PAC_MTRS": 0,
            "ORD_MTRS": 0,
            "BAL_QTY": 4544.0032,
            "DYG_PCS": 0,
            "DYG_MTRS": 0,
            "PO_MTRS": 0,
            "BASE_DESIGN": null,
            "SIMILAR_DESIGN": null,
            "BASE_QUALITY": null,
            "SIMILAR_QUALITY": null,
            "dsnoid": 12179
        },
        {
            "QUALITY": "Filafil",
            "DESIGN": 257,
            "FAC_PCS": 21,
            "FAC_MTRS": 872,
            "PAC_PCS": 0,
            "PAC_MTRS": 0,
            "ORD_MTRS": 0,
            "BAL_QTY": 872,
            "DYG_PCS": 0,
            "DYG_MTRS": 0,
            "PO_MTRS": 3600,
            "BASE_DESIGN": null,
            "SIMILAR_DESIGN": null,
            "BASE_QUALITY": null,
            "SIMILAR_QUALITY": null,
            "dsnoid": 22334
        },
        {
            "QUALITY": "Filafil",
            "DESIGN": 255,
            "FAC_PCS": 21,
            "FAC_MTRS": 1427.202,
            "PAC_PCS": 0,
            "PAC_MTRS": 0,
            "ORD_MTRS": 12012.8,
            "BAL_QTY": -10585.598,
            "DYG_PCS": 0,
            "DYG_MTRS": 0,
            "PO_MTRS": 21000,
            "BASE_DESIGN": null,
            "SIMILAR_DESIGN": null,
            "BASE_QUALITY": null,
            "SIMILAR_QUALITY": null,
            "dsnoid": 24228
        },
        {
            "QUALITY": "Filafil",
            "DESIGN": 252,
            "FAC_PCS": 87,
            "FAC_MTRS": 6412.6008,
            "PAC_PCS": 0,
            "PAC_MTRS": 0,
            "ORD_MTRS": 0,
            "BAL_QTY": 6412.6008,
            "DYG_PCS": 2,
            "DYG_MTRS": 206,
            "PO_MTRS": 20000,
            "BASE_DESIGN": null,
            "SIMILAR_DESIGN": null,
            "BASE_QUALITY": null,
            "SIMILAR_QUALITY": null,
            "dsnoid": 28122
        }
    ];
